### ISSUE TITLE
Subscriptions Management: Shipping costs cannot be updated when adding products to subscriptions

### ISSUE THREAD

**Issue by franticpsyx** [somewherewarm/woocommerce-subscribe-all-the-things#280]
When adding products to subscriptions, the recurring shipping cost in the subscription object isn't modified.

That's OK when charging a flat shipping fee, but otherwise it's a significant limitation. For most applications of "adding physical products to subs", that's a reasonable limitation. I'd guess that most stores shipping physical goods on a recurring basis charge a flat shipping fee, but we'd need to validate that assumption after SATT 2.1 has been out in the wild for a few months at least.

Solving this in a general, reliable way is not going to be easy. Not only because the solution we'd come up with would likely be very hacky, but also because designing a good, general flow for this is almost impossible IMO.

We could try to recreate the original shipping package contents and get WC to recalculate shipping, but we don't know how the original rate was generated (via an API?) and in general can't easily "match" the original rate with a recalculated version of it.

IMO this is something that developers consuming SATT will need to address on their side in a case-specific manner. I'm not sure if we can do something to facilitate that?

Marking as won't fix for now, as the switching module of WCS has a similar limitation:

Related: https://github.com/Prospress/woocommerce-subscriptions/issues/2518

cc @thenbrent

**Comment by javorszky** [comment]
Currently recalculating shipping depends on a lot of things. For one, it needs an instance of a cart, which needs an instance of a customer - both are things that are only available on the front end.

Then the packages of the order need to be turned into shipping packages (not an easy thing to do), and then the chosen shipping method queried whether the new # of items / weight is still supported.

Then if it's no longer supported, all other shipping methods in that zone need to be queried, and then one chosen.

Because there are several choices here that need making that potentially include human interaction (need to choose a new shipping method for example), I'm not sure it can be generally implemented without significant limitations.

**Comment by franticpsyx** [comment]
Thanks for confirming @javorszky -- I thought I'd create and leave this issue open as a placeholder to help answer any questions we'll likely get in the future. I don't think there's a general solution here without requiring interaction.

We _could_ possibly design a flow that requires the customer adding a product/cart to a subscription to choose a new rate for the modified subscription, but that wouldn't be easy and I'm not willing to delve into it until we have sufficient evidence that it's a vital feature for lots of folks using add-to-sub features.

**Comment by franticpsyx** [comment]
> I don't think there's a general solution here that doesn't rely on user/customer interaction.

PS: Even if there was a solution, modifying shipping costs without explicit user/customer knowledge would be a bad idea. If a user/customer adds something to their subscription and that ends up increasing the shipping cost to something they are not willing to pay, they should be able to back off. Similarly, if there are multiple possible rates to choose from, they should be able to pick the one they want.

**Comment by franticpsyx** [comment]
Moved to the [APFS](https://github.com/somewherewarm/woocommerce-subscribe-all-the-things/issues/436) repository.
