### ISSUE TITLE
Cart Subscription Discounts

### ISSUE THREAD

**Issue by fcponline** [somewherewarm/woocommerce-subscribe-all-the-things#57]
Hello,

Is it possible to add discounts to the Subscribe to Cart settings like in the individual product subscription settings?

This would be an excellent feature.

Thanks,

FCP

**Comment by fcponline** [comment]
If we can apply discounts to individual product why cant they be applied at the entire cart level?

We have created a work around by dynamically applying coupons based on Subscription timeframe chosen. It works when we create all the button and actions. Not the most scalable solution.

**Comment by franticpsyx** [comment]
Hey @fcponline - thanks for the feedback!

This is definitely on our radar, but unfortunately I don't have an ETA for this feature at the moment.

**Comment by seb86** [comment]
@fcponline Can you share your work around? Maybe we can use it as a starting point.

**Comment by fcponline** [comment]
Hello guys @seb86 @franticpsyx Happy end of the summer! ;)

Our work around relies on WC Coupons / Super Coupons plugin that allows you to create all sorts of coupons.  Essentially from select places on our site we have used ajax to call on a custom function that applied the coupon that we have associated with the Subscr Timeframe...

Here is the basic code in the function...

`<?php
include('../../../wp-load.php'); 
include('../../../wp-config.php'); 
//include('wp-load.php');
//include('wp-config.php');
global $woocommerce;

extract($_POST);
if($selected_scheme=='1_month_3')
{
    $woocommerce->cart->remove_coupons();
    $woocommerce->cart->add_discount( sanitize_text_field('5% discount'));
}
else if($selected_scheme=='1_month_6')
{
    $woocommerce->cart->remove_coupons();
    $woocommerce->cart->add_discount( sanitize_text_field('10% discount'));
}
else if($selected_scheme=='1_month_12')
{
    $woocommerce->cart->remove_coupons();
    $woocommerce->cart->add_discount( sanitize_text_field('15% discount'));
}
else
{
    $woocommerce->cart->remove_coupons();
}
//$woocommerce->cart->add_discount( sanitize_text_field('10% discount'));

?>`

Hope that helps. Let me know if you need more.

-- fpc

**Comment by ash-f** [comment]
I want to know simple way to check see if item is subscription.
So far only way I can judge see if cart item is subscription is:
`global $woocommerce;
$cart = $woocommerce->cart->get_cart();
foreach($cart as $ck=>$cv){
  if(!empty($cv['wccsub_data']['active_subscription_scheme_id'])){
    return true;
  }
}`

Is there way to check it more simply?

**Comment by franticpsyx** [comment]
@ash-f For now you can use:

- `WCS_ATT_Schemes::get_active_subscription_scheme( $cart_item )`; and/or
- `isset( $cart_item[ 'data' ]->is_converted_to_sub ) && 'yes' === $cart_item[ 'data' ]->is_converted_to_sub`

We are planning to write a Product API for getting/setting subscription data from/to product instances (see https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/42) but this might get delayed a bit due to the release of WC 2.7. 

WC 2.7 requires all extensions in the Subscriptions/SATT ecosystem to be updated in order to be compatible, so at the moment features development in SATT is in freeze mode as we look into / implement the required changes. @thenbrent

**Comment by pprotschka** [comment]
@fcponline 
i probably will need use the same approach by applying the coupons dynamically. 
When/Where are you placing that code?

for me it would be ideal if it was hooked when the ajax call from changing SATT option in the cart was trigged? 
any pointers?

**Comment by fcponline** [comment]
@pprotschka 

We added the code to a Submit button on a custom order from that we have created. The form allows the user to choose the amount of individual products in a Product Bundle.  Then we created a custom radio box that allows the person to select the timeframe & discount that they want...

8 weeks = 10%
16 weeks = 20%
etc...

Then we applied the WC Coupons / Super Coupons plugin code to the Product Bundle.

Product Bundle x 1
--- Item 101 x 5
--- Item 102 x 3
--- Item 103 x 1
Sub Total = 100.00

Discount = 10%
Discount Subtotal = 10.00

Total = 90.00

**Comment by freddiehonohan** [comment]
I have been tasked with adding this functionality for a friends website however this is only my first foray into wordpress plugins so if anybody would like to bullet point the general approach I could attempt this.

As far as I can see, there needs to be a simple discount field added to the option form in the settings view for the backend here:
![image](https://user-images.githubusercontent.com/3375175/35813924-bf984f96-0a8c-11e8-97a5-8e1f74f2dd01.png)

And there'd need to be some frontend adjustments also to display the discount amount (to entice the user into the subscription) at the checkout screen. The simplest thing to deal with individual product discounts and coupon codes would be to nullify them and perhaps this would be the best starting point.

Thanks

**Comment by franticpsyx** [comment]
Hey @freddiehonohan

This is definitely on the roadmap but it's not part of the 2.1 release cycle. While I can safely it will be included the 2.2 release, I can't provide an exact ETA. I don't expect any work on this to start in the next 3-4 weeks. If you think you can contribute a solution that adheres to SATT/WC conventions and [WordPress coding standards](https://codex.wordpress.org/WordPress_Coding_Standards) feel free to give this a shot and submit a PR.

Due to the relatively extended scope of this feature I'm afraid I can't provide much help with the actual implementation. Generally speaking, however, global schemes and product-level schemes are handled exactly the same, so if you:

* port the necessary fields over from product-level schemes (Price Override / Discount); and
* process/save them in global schemes,

then the specified discount will be applied when choosing a cart-level (global) subscription scheme, as cart-level (global) schemes are saved on product objects in the cart just like product-level schemes.

Once complication that will need to be worked out is the need to display a (discounted) price amount along with the cart-level subscription scheme details -- and the only way to get that would be to look at cart totals.

If your friend is not in a hurry, you might be better off waiting for the 2.2 release than working it all out (WooCommerce / Subscriptions / Subscribe All the Things) yourself :)

**Comment by freddiehonohan** [comment]
Yeah, that's exactly what I thought. The domain of the problem extends across several plugins (WooCommerce / Subscriptions / Subscribe All the Things) and I'd need to fully understand each of them to provide a fault-less solution.

Thanks for the pointers anyway, if I take this on you'll hear from me!

**Comment by aloco** [comment]
Hi, as you all have already discussed, subscription cart discounts can be achieved by using coupons. You can use the Plugin https://wordpress.org/plugins/woocommerce-auto-added-coupons/ to auto apply a coupon, based on a certain condition (like if a subscription is used). The plugin also supports to silently add a coupon. This works for me to apply a discount when choosing a cart subscription without displaying the woocommerce coupon notification. JFYI ✌️

**Comment by franticpsyx** [comment]
Implemented in APFS 2.2.
